databases:
  - name: todo
    plan: free
    databaseName: tododb
    user: tododb_owner

services:
  - type: web
    plan: free
    name: todo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4